# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 500)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background-color:white;")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.menu = QtWidgets.QFrame(self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(0, 0, 131, 481))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        self.menu.setStyleSheet("")
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.change_info = QtWidgets.QPushButton(self.menu)
        self.change_info.setGeometry(QtCore.QRect(0, 370, 130, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.change_info.sizePolicy().hasHeightForWidth())
        self.change_info.setSizePolicy(sizePolicy)
        self.change_info.setStyleSheet("margin:10px;\n"
"border-radius: 15px;\n"
"border:3px solid teal;\n"
"")
        self.change_info.setObjectName("change_info")
        self.get_info = QtWidgets.QPushButton(self.menu)
        self.get_info.setGeometry(QtCore.QRect(0, 40, 130, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_info.sizePolicy().hasHeightForWidth())
        self.get_info.setSizePolicy(sizePolicy)
        self.get_info.setStyleSheet("margin:10px;\n"
"border-radius: 15px;\n"
"border:3px solid teal;\n"
"")
        self.get_info.setObjectName("get_info")
        self.login = QtWidgets.QPushButton(self.menu)
        self.login.setGeometry(QtCore.QRect(20, 430, 90, 50))
        self.login.setStyleSheet("margin:10px;\n"
"border-radius: 15px;\n"
"border:3px solid teal;\n"
"")
        self.login.setObjectName("login")
        self.additional_info = QtWidgets.QPushButton(self.menu)
        self.additional_info.setGeometry(QtCore.QRect(0, 100, 130, 60))
        self.additional_info.setStyleSheet("margin:10px;\n"
"border-radius: 15px;\n"
"border:3px solid teal;\n"
"")
        self.additional_info.setObjectName("additional_info")
        self.view_info_admin = QtWidgets.QPushButton(self.menu)
        self.view_info_admin.setGeometry(QtCore.QRect(0, 310, 130, 60))
        self.view_info_admin.setStyleSheet("margin:10px;\n"
"border-radius: 15px;\n"
"border:3px solid teal;\n"
"")
        self.view_info_admin.setObjectName("view_info_admin")
        self.label_6 = QtWidgets.QLabel(self.menu)
        self.label_6.setGeometry(QtCore.QRect(50, 20, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.menu)
        self.label_7.setGeometry(QtCore.QRect(40, 290, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(140, 0, 671, 501))
        self.stackedWidget.setStyleSheet("border:none;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("")
        self.page.setObjectName("page")
        self.frame_1 = QtWidgets.QFrame(self.page)
        self.frame_1.setGeometry(QtCore.QRect(0, 0, 691, 501))
        self.frame_1.setStyleSheet("")
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.label = QtWidgets.QLabel(self.frame_1)
        self.label.setGeometry(QtCore.QRect(30, 10, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_1)
        self.tabWidget.setGeometry(QtCore.QRect(20, 50, 601, 391))
        self.tabWidget.setMinimumSize(QtCore.QSize(251, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.flight_info_by_number_list = QtWidgets.QListWidget(self.tab_3)
        self.flight_info_by_number_list.setGeometry(QtCore.QRect(10, 100, 581, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.flight_info_by_number_list.setFont(font)
        self.flight_info_by_number_list.setStyleSheet("border:none;")
        self.flight_info_by_number_list.setObjectName("flight_info_by_number_list")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.find_info_number_btn = QtWidgets.QPushButton(self.tab_3)
        self.find_info_number_btn.setGeometry(QtCore.QRect(30, 60, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.find_info_number_btn.setFont(font)
        self.find_info_number_btn.setStyleSheet("border:2px solid teal;\n"
"border-radius:5px;")
        self.find_info_number_btn.setObjectName("find_info_number_btn")
        self.enter_number = QtWidgets.QLineEdit(self.tab_3)
        self.enter_number.setGeometry(QtCore.QRect(180, 20, 113, 20))
        self.enter_number.setStyleSheet("border:1px solid;")
        self.enter_number.setObjectName("enter_number")
        self.find_number_error = QtWidgets.QLabel(self.tab_3)
        self.find_number_error.setGeometry(QtCore.QRect(340, 20, 110, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.find_number_error.setFont(font)
        self.find_number_error.setStyleSheet("border:none;\n"
"color:orange;")
        self.find_number_error.setText("")
        self.find_number_error.setObjectName("find_number_error")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.departure_input = QtWidgets.QLineEdit(self.tab_2)
        self.departure_input.setGeometry(QtCore.QRect(130, 20, 113, 20))
        self.departure_input.setStyleSheet("border:1px solid;")
        self.departure_input.setObjectName("departure_input")
        self.find_info_direction_btn = QtWidgets.QPushButton(self.tab_2)
        self.find_info_direction_btn.setGeometry(QtCore.QRect(30, 60, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.find_info_direction_btn.setFont(font)
        self.find_info_direction_btn.setStyleSheet("border:2px solid teal;\n"
"border-radius:5px;")
        self.find_info_direction_btn.setObjectName("find_info_direction_btn")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.flight_info_by_direction_list = QtWidgets.QListWidget(self.tab_2)
        self.flight_info_by_direction_list.setGeometry(QtCore.QRect(10, 100, 581, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.flight_info_by_direction_list.setFont(font)
        self.flight_info_by_direction_list.setStyleSheet("border:none;")
        self.flight_info_by_direction_list.setObjectName("flight_info_by_direction_list")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(320, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.arrival_input = QtWidgets.QLineEdit(self.tab_2)
        self.arrival_input.setGeometry(QtCore.QRect(390, 20, 113, 20))
        self.arrival_input.setStyleSheet("border:1px solid;")
        self.arrival_input.setObjectName("arrival_input")
        self.find_direction_error = QtWidgets.QLabel(self.tab_2)
        self.find_direction_error.setGeometry(QtCore.QRect(240, 60, 110, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.find_direction_error.setFont(font)
        self.find_direction_error.setStyleSheet("border:none;\n"
"color:orange;")
        self.find_direction_error.setText("")
        self.find_direction_error.setObjectName("find_direction_error")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.flight_info_by_date_list = QtWidgets.QListWidget(self.tab_1)
        self.flight_info_by_date_list.setGeometry(QtCore.QRect(10, 100, 581, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.flight_info_by_date_list.setFont(font)
        self.flight_info_by_date_list.setStyleSheet("")
        self.flight_info_by_date_list.setObjectName("flight_info_by_date_list")
        self.date_input = QtWidgets.QLineEdit(self.tab_1)
        self.date_input.setGeometry(QtCore.QRect(130, 20, 113, 20))
        self.date_input.setStyleSheet("border:1px solid;")
        self.date_input.setObjectName("date_input")
        self.label_5 = QtWidgets.QLabel(self.tab_1)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.find_info_date_btn = QtWidgets.QPushButton(self.tab_1)
        self.find_info_date_btn.setGeometry(QtCore.QRect(30, 60, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.find_info_date_btn.setFont(font)
        self.find_info_date_btn.setStyleSheet("border:2px solid teal;\n"
"border-radius:5px;")
        self.find_info_date_btn.setObjectName("find_info_date_btn")
        self.date_input_error = QtWidgets.QLabel(self.tab_1)
        self.date_input_error.setGeometry(QtCore.QRect(290, 20, 110, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.date_input_error.setFont(font)
        self.date_input_error.setStyleSheet("border:none;\n"
"color:orange;")
        self.date_input_error.setText("")
        self.date_input_error.setObjectName("date_input_error")
        self.tabWidget.addTab(self.tab_1, "")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.page_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 20, 671, 441))
        self.tabWidget_2.setMinimumSize(QtCore.QSize(251, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setStyleSheet("")
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_2.setUsesScrollButtons(True)
        self.tabWidget_2.setDocumentMode(False)
        self.tabWidget_2.setTabsClosable(False)
        self.tabWidget_2.setMovable(False)
        self.tabWidget_2.setTabBarAutoHide(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(30, 20, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.get_number_of_free_seats_btn = QtWidgets.QPushButton(self.tab_4)
        self.get_number_of_free_seats_btn.setGeometry(QtCore.QRect(30, 60, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.get_number_of_free_seats_btn.setFont(font)
        self.get_number_of_free_seats_btn.setStyleSheet("border:2px solid teal;\n"
"border-radius:5px;")
        self.get_number_of_free_seats_btn.setObjectName("get_number_of_free_seats_btn")
        self.free_seats_number_input = QtWidgets.QLineEdit(self.tab_4)
        self.free_seats_number_input.setGeometry(QtCore.QRect(180, 20, 113, 20))
        self.free_seats_number_input.setStyleSheet("border:1px solid;")
        self.free_seats_number_input.setObjectName("free_seats_number_input")
        self.free_seats_number_input_error = QtWidgets.QLabel(self.tab_4)
        self.free_seats_number_input_error.setGeometry(QtCore.QRect(340, 20, 110, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.free_seats_number_input_error.setFont(font)
        self.free_seats_number_input_error.setStyleSheet("border:none;\n"
"color:orange;")
        self.free_seats_number_input_error.setText("")
        self.free_seats_number_input_error.setObjectName("free_seats_number_input_error")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(30, 110, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.number_of_free_seats = QtWidgets.QLabel(self.tab_4)
        self.number_of_free_seats.setGeometry(QtCore.QRect(220, 110, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.number_of_free_seats.setFont(font)
        self.number_of_free_seats.setText("")
        self.number_of_free_seats.setObjectName("number_of_free_seats")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.baggage_sum_number_input = QtWidgets.QLineEdit(self.tab_5)
        self.baggage_sum_number_input.setGeometry(QtCore.QRect(180, 20, 113, 20))
        self.baggage_sum_number_input.setStyleSheet("border:1px solid;")
        self.baggage_sum_number_input.setObjectName("baggage_sum_number_input")
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        self.label_13.setGeometry(QtCore.QRect(30, 110, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.get_baggage_sum_btn = QtWidgets.QPushButton(self.tab_5)
        self.get_baggage_sum_btn.setGeometry(QtCore.QRect(30, 60, 131, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.get_baggage_sum_btn.setFont(font)
        self.get_baggage_sum_btn.setStyleSheet("border:2px solid teal;\n"
"border-radius:5px;")
        self.get_baggage_sum_btn.setObjectName("get_baggage_sum_btn")
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        self.label_9.setGeometry(QtCore.QRect(30, 20, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.baggage_sum_number_input_error = QtWidgets.QLabel(self.tab_5)
        self.baggage_sum_number_input_error.setGeometry(QtCore.QRect(340, 20, 110, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.baggage_sum_number_input_error.setFont(font)
        self.baggage_sum_number_input_error.setStyleSheet("border:none;\n"
"color:orange;")
        self.baggage_sum_number_input_error.setText("")
        self.baggage_sum_number_input_error.setObjectName("baggage_sum_number_input_error")
        self.baggage_sum = QtWidgets.QLabel(self.tab_5)
        self.baggage_sum.setGeometry(QtCore.QRect(220, 110, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.baggage_sum.setFont(font)
        self.baggage_sum.setText("")
        self.baggage_sum.setObjectName("baggage_sum")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action12 = QtWidgets.QAction(MainWindow)
        self.action12.setObjectName("action12")
        self.action12_2 = QtWidgets.QAction(MainWindow)
        self.action12_2.setObjectName("action12_2")
        self.action1_1 = QtWidgets.QAction(MainWindow)
        self.action1_1.setObjectName("action1_1")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.change_info.setText(_translate("MainWindow", "Change flight info"))
        self.get_info.setText(_translate("MainWindow", "View flight info"))
        self.login.setText(_translate("MainWindow", "Login"))
        self.additional_info.setText(_translate("MainWindow", "Additional info"))
        self.view_info_admin.setText(_translate("MainWindow", "View flight info"))
        self.label_6.setText(_translate("MainWindow", "User"))
        self.label_7.setText(_translate("MainWindow", "Admin"))
        self.label.setText(_translate("MainWindow", "Find flights information by"))
        self.label_2.setText(_translate("MainWindow", "Enter flight number"))
        self.find_info_number_btn.setText(_translate("MainWindow", "Find"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Number"))
        self.find_info_direction_btn.setText(_translate("MainWindow", "Find"))
        self.label_3.setText(_translate("MainWindow", "Departure"))
        self.label_4.setText(_translate("MainWindow", "Arrival"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Direction"))
        self.label_5.setText(_translate("MainWindow", "Enter date"))
        self.find_info_date_btn.setText(_translate("MainWindow", "Find"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Date"))
        self.label_8.setText(_translate("MainWindow", "Enter flight number"))
        self.get_number_of_free_seats_btn.setText(_translate("MainWindow", "Get free seats"))
        self.label_12.setText(_translate("MainWindow", "Number of free seats:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Free seats"))
        self.label_13.setText(_translate("MainWindow", "Number of free seats:"))
        self.get_baggage_sum_btn.setText(_translate("MainWindow", "Get sum of baggage"))
        self.label_9.setText(_translate("MainWindow", "Enter flight number"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Sum of baggage"))
        self.action2.setText(_translate("MainWindow", "2"))
        self.action12.setText(_translate("MainWindow", "11"))
        self.action12_2.setText(_translate("MainWindow", "12"))
        self.action1_1.setText(_translate("MainWindow", "1.1"))
