# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background-color:white;")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.menu = QtWidgets.QFrame(self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(0, 0, 131, 481))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        self.menu.setStyleSheet("")
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.insert_info = QtWidgets.QPushButton(self.menu)
        self.insert_info.setGeometry(QtCore.QRect(0, 370, 130, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insert_info.sizePolicy().hasHeightForWidth())
        self.insert_info.setSizePolicy(sizePolicy)
        self.insert_info.setStyleSheet("margin:10px;\n"
"border-radius: 15px;\n"
"border:3px solid teal;\n"
"")
        self.insert_info.setObjectName("insert_info")
        self.get_info = QtWidgets.QPushButton(self.menu)
        self.get_info.setGeometry(QtCore.QRect(0, 40, 130, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_info.sizePolicy().hasHeightForWidth())
        self.get_info.setSizePolicy(sizePolicy)
        self.get_info.setStyleSheet("margin:10px;\n"
"border-radius: 15px;\n"
"border:3px solid teal;\n"
"")
        self.get_info.setObjectName("get_info")
        self.login = QtWidgets.QPushButton(self.menu)
        self.login.setGeometry(QtCore.QRect(20, 430, 90, 50))
        self.login.setStyleSheet("margin:10px;\n"
"border-radius: 15px;\n"
"border:3px solid teal;\n"
"")
        self.login.setObjectName("login")
        self.additional_info = QtWidgets.QPushButton(self.menu)
        self.additional_info.setGeometry(QtCore.QRect(0, 100, 130, 60))
        self.additional_info.setStyleSheet("margin:10px;\n"
"border-radius: 15px;\n"
"border:3px solid teal;")
        self.additional_info.setObjectName("additional_info")
        self.view_info_admin = QtWidgets.QPushButton(self.menu)
        self.view_info_admin.setGeometry(QtCore.QRect(0, 310, 130, 60))
        self.view_info_admin.setStyleSheet("margin:10px;\n"
"border-radius: 15px;\n"
"border:3px solid teal;\n"
"")
        self.view_info_admin.setObjectName("view_info_admin")
        self.label_6 = QtWidgets.QLabel(self.menu)
        self.label_6.setGeometry(QtCore.QRect(50, 20, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.menu)
        self.label_7.setGeometry(QtCore.QRect(40, 290, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(140, 0, 661, 501))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("border:none;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("")
        self.page.setObjectName("page")
        self.frame_1 = QtWidgets.QFrame(self.page)
        self.frame_1.setGeometry(QtCore.QRect(0, 0, 691, 501))
        self.frame_1.setStyleSheet("")
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.label = QtWidgets.QLabel(self.frame_1)
        self.label.setGeometry(QtCore.QRect(30, 10, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_1)
        self.tabWidget.setGeometry(QtCore.QRect(20, 60, 601, 391))
        self.tabWidget.setMinimumSize(QtCore.QSize(251, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.flight_info_by_number_list = QtWidgets.QListWidget(self.tab_3)
        self.flight_info_by_number_list.setGeometry(QtCore.QRect(10, 100, 581, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.flight_info_by_number_list.setFont(font)
        self.flight_info_by_number_list.setStyleSheet("border:none;")
        self.flight_info_by_number_list.setObjectName("flight_info_by_number_list")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.find_info_number_btn = QtWidgets.QPushButton(self.tab_3)
        self.find_info_number_btn.setGeometry(QtCore.QRect(30, 60, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.find_info_number_btn.setFont(font)
        self.find_info_number_btn.setStyleSheet("border:2px solid teal;\n"
"border-radius:5px;")
        self.find_info_number_btn.setObjectName("find_info_number_btn")
        self.enter_number = QtWidgets.QLineEdit(self.tab_3)
        self.enter_number.setGeometry(QtCore.QRect(180, 20, 113, 20))
        self.enter_number.setStyleSheet("border:1px solid;")
        self.enter_number.setObjectName("enter_number")
        self.find_number_error = QtWidgets.QLabel(self.tab_3)
        self.find_number_error.setGeometry(QtCore.QRect(340, 20, 110, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.find_number_error.setFont(font)
        self.find_number_error.setStyleSheet("border:none;\n"
"color:orange;")
        self.find_number_error.setText("")
        self.find_number_error.setObjectName("find_number_error")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.departure_input = QtWidgets.QLineEdit(self.tab_2)
        self.departure_input.setGeometry(QtCore.QRect(130, 20, 113, 20))
        self.departure_input.setStyleSheet("border:1px solid;")
        self.departure_input.setObjectName("departure_input")
        self.find_info_direction_btn = QtWidgets.QPushButton(self.tab_2)
        self.find_info_direction_btn.setGeometry(QtCore.QRect(30, 60, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.find_info_direction_btn.setFont(font)
        self.find_info_direction_btn.setStyleSheet("border:2px solid teal;\n"
"border-radius:5px;")
        self.find_info_direction_btn.setObjectName("find_info_direction_btn")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.flight_info_by_direction_list = QtWidgets.QListWidget(self.tab_2)
        self.flight_info_by_direction_list.setGeometry(QtCore.QRect(10, 100, 581, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.flight_info_by_direction_list.setFont(font)
        self.flight_info_by_direction_list.setStyleSheet("border:none;")
        self.flight_info_by_direction_list.setObjectName("flight_info_by_direction_list")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(320, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.arrival_input = QtWidgets.QLineEdit(self.tab_2)
        self.arrival_input.setGeometry(QtCore.QRect(390, 20, 113, 20))
        self.arrival_input.setStyleSheet("border:1px solid;")
        self.arrival_input.setObjectName("arrival_input")
        self.find_direction_error = QtWidgets.QLabel(self.tab_2)
        self.find_direction_error.setGeometry(QtCore.QRect(240, 60, 110, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.find_direction_error.setFont(font)
        self.find_direction_error.setStyleSheet("border:none;\n"
"color:orange;")
        self.find_direction_error.setText("")
        self.find_direction_error.setObjectName("find_direction_error")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.flight_info_by_date_list = QtWidgets.QListWidget(self.tab_1)
        self.flight_info_by_date_list.setGeometry(QtCore.QRect(10, 100, 581, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.flight_info_by_date_list.setFont(font)
        self.flight_info_by_date_list.setStyleSheet("")
        self.flight_info_by_date_list.setObjectName("flight_info_by_date_list")
        self.date_input = QtWidgets.QLineEdit(self.tab_1)
        self.date_input.setGeometry(QtCore.QRect(130, 20, 113, 20))
        self.date_input.setStyleSheet("border:1px solid;")
        self.date_input.setObjectName("date_input")
        self.label_5 = QtWidgets.QLabel(self.tab_1)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.find_info_date_btn = QtWidgets.QPushButton(self.tab_1)
        self.find_info_date_btn.setGeometry(QtCore.QRect(30, 60, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.find_info_date_btn.setFont(font)
        self.find_info_date_btn.setStyleSheet("border:2px solid teal;\n"
"border-radius:5px;")
        self.find_info_date_btn.setObjectName("find_info_date_btn")
        self.date_input_error = QtWidgets.QLabel(self.tab_1)
        self.date_input_error.setGeometry(QtCore.QRect(290, 20, 110, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.date_input_error.setFont(font)
        self.date_input_error.setStyleSheet("border:none;\n"
"color:orange;")
        self.date_input_error.setText("")
        self.date_input_error.setObjectName("date_input_error")
        self.tabWidget.addTab(self.tab_1, "")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.page_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 20, 671, 441))
        self.tabWidget_2.setMinimumSize(QtCore.QSize(251, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setStyleSheet("")
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_2.setUsesScrollButtons(True)
        self.tabWidget_2.setDocumentMode(False)
        self.tabWidget_2.setTabsClosable(False)
        self.tabWidget_2.setMovable(False)
        self.tabWidget_2.setTabBarAutoHide(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(30, 20, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.get_number_of_free_seats_btn = QtWidgets.QPushButton(self.tab_4)
        self.get_number_of_free_seats_btn.setGeometry(QtCore.QRect(30, 60, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.get_number_of_free_seats_btn.setFont(font)
        self.get_number_of_free_seats_btn.setStyleSheet("border:2px solid teal;\n"
"border-radius:5px;")
        self.get_number_of_free_seats_btn.setObjectName("get_number_of_free_seats_btn")
        self.free_seats_number_input = QtWidgets.QLineEdit(self.tab_4)
        self.free_seats_number_input.setGeometry(QtCore.QRect(180, 20, 113, 20))
        self.free_seats_number_input.setStyleSheet("border:1px solid;")
        self.free_seats_number_input.setObjectName("free_seats_number_input")
        self.free_seats_number_input_error = QtWidgets.QLabel(self.tab_4)
        self.free_seats_number_input_error.setGeometry(QtCore.QRect(340, 20, 110, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.free_seats_number_input_error.setFont(font)
        self.free_seats_number_input_error.setStyleSheet("border:none;\n"
"color:orange;")
        self.free_seats_number_input_error.setText("")
        self.free_seats_number_input_error.setObjectName("free_seats_number_input_error")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(30, 110, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.number_of_free_seats = QtWidgets.QLabel(self.tab_4)
        self.number_of_free_seats.setGeometry(QtCore.QRect(220, 110, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.number_of_free_seats.setFont(font)
        self.number_of_free_seats.setText("")
        self.number_of_free_seats.setObjectName("number_of_free_seats")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.baggage_sum_number_input = QtWidgets.QLineEdit(self.tab_5)
        self.baggage_sum_number_input.setGeometry(QtCore.QRect(180, 20, 113, 20))
        self.baggage_sum_number_input.setStyleSheet("border:1px solid;")
        self.baggage_sum_number_input.setObjectName("baggage_sum_number_input")
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        self.label_13.setGeometry(QtCore.QRect(30, 110, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.get_baggage_sum_btn = QtWidgets.QPushButton(self.tab_5)
        self.get_baggage_sum_btn.setGeometry(QtCore.QRect(30, 60, 131, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.get_baggage_sum_btn.setFont(font)
        self.get_baggage_sum_btn.setStyleSheet("border:2px solid teal;\n"
"border-radius:5px;")
        self.get_baggage_sum_btn.setObjectName("get_baggage_sum_btn")
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        self.label_9.setGeometry(QtCore.QRect(30, 20, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.baggage_sum_number_input_error = QtWidgets.QLabel(self.tab_5)
        self.baggage_sum_number_input_error.setGeometry(QtCore.QRect(340, 20, 110, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.baggage_sum_number_input_error.setFont(font)
        self.baggage_sum_number_input_error.setStyleSheet("border:none;\n"
"color:orange;")
        self.baggage_sum_number_input_error.setText("")
        self.baggage_sum_number_input_error.setObjectName("baggage_sum_number_input_error")
        self.baggage_sum = QtWidgets.QLabel(self.tab_5)
        self.baggage_sum.setGeometry(QtCore.QRect(220, 110, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.baggage_sum.setFont(font)
        self.baggage_sum.setText("")
        self.baggage_sum.setObjectName("baggage_sum")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_10 = QtWidgets.QLabel(self.page_3)
        self.label_10.setGeometry(QtCore.QRect(20, 10, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.page_3)
        self.tabWidget_3.setGeometry(QtCore.QRect(20, 60, 601, 391))
        self.tabWidget_3.setMinimumSize(QtCore.QSize(251, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setStyleSheet("")
        self.tabWidget_3.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_3.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_3.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget_3.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_3.setUsesScrollButtons(True)
        self.tabWidget_3.setDocumentMode(False)
        self.tabWidget_3.setTabsClosable(False)
        self.tabWidget_3.setMovable(False)
        self.tabWidget_3.setTabBarAutoHide(False)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.flight_info_by_surname_list = QtWidgets.QListWidget(self.tab_6)
        self.flight_info_by_surname_list.setGeometry(QtCore.QRect(10, 100, 581, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.flight_info_by_surname_list.setFont(font)
        self.flight_info_by_surname_list.setStyleSheet("border:none;")
        self.flight_info_by_surname_list.setObjectName("flight_info_by_surname_list")
        self.label_16 = QtWidgets.QLabel(self.tab_6)
        self.label_16.setGeometry(QtCore.QRect(30, 20, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.find_info_surname_btn = QtWidgets.QPushButton(self.tab_6)
        self.find_info_surname_btn.setGeometry(QtCore.QRect(30, 60, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.find_info_surname_btn.setFont(font)
        self.find_info_surname_btn.setStyleSheet("border:2px solid teal;\n"
"border-radius:5px;")
        self.find_info_surname_btn.setObjectName("find_info_surname_btn")
        self.surname_input = QtWidgets.QLineEdit(self.tab_6)
        self.surname_input.setGeometry(QtCore.QRect(180, 20, 113, 20))
        self.surname_input.setStyleSheet("border:1px solid;")
        self.surname_input.setObjectName("surname_input")
        self.find_surname_error = QtWidgets.QLabel(self.tab_6)
        self.find_surname_error.setGeometry(QtCore.QRect(340, 20, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.find_surname_error.setFont(font)
        self.find_surname_error.setStyleSheet("border:none;\n"
"color:orange;")
        self.find_surname_error.setText("")
        self.find_surname_error.setObjectName("find_surname_error")
        self.tabWidget_3.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.departure_input_2 = QtWidgets.QLineEdit(self.tab_7)
        self.departure_input_2.setGeometry(QtCore.QRect(130, 20, 113, 20))
        self.departure_input_2.setStyleSheet("border:1px solid;")
        self.departure_input_2.setObjectName("departure_input_2")
        self.find_info_direction_btn_2 = QtWidgets.QPushButton(self.tab_7)
        self.find_info_direction_btn_2.setGeometry(QtCore.QRect(30, 60, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.find_info_direction_btn_2.setFont(font)
        self.find_info_direction_btn_2.setStyleSheet("border:2px solid teal;\n"
"border-radius:5px;")
        self.find_info_direction_btn_2.setObjectName("find_info_direction_btn_2")
        self.label_17 = QtWidgets.QLabel(self.tab_7)
        self.label_17.setGeometry(QtCore.QRect(30, 20, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.flight_info_by_direction_list_2 = QtWidgets.QListWidget(self.tab_7)
        self.flight_info_by_direction_list_2.setGeometry(QtCore.QRect(10, 100, 581, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.flight_info_by_direction_list_2.setFont(font)
        self.flight_info_by_direction_list_2.setStyleSheet("border:none;")
        self.flight_info_by_direction_list_2.setObjectName("flight_info_by_direction_list_2")
        self.label_18 = QtWidgets.QLabel(self.tab_7)
        self.label_18.setGeometry(QtCore.QRect(320, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.arrival_input_2 = QtWidgets.QLineEdit(self.tab_7)
        self.arrival_input_2.setGeometry(QtCore.QRect(390, 20, 113, 20))
        self.arrival_input_2.setStyleSheet("border:1px solid;")
        self.arrival_input_2.setObjectName("arrival_input_2")
        self.find_direction_error_2 = QtWidgets.QLabel(self.tab_7)
        self.find_direction_error_2.setGeometry(QtCore.QRect(240, 60, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.find_direction_error_2.setFont(font)
        self.find_direction_error_2.setStyleSheet("border:none;\n"
"color:orange;")
        self.find_direction_error_2.setText("")
        self.find_direction_error_2.setObjectName("find_direction_error_2")
        self.tabWidget_3.addTab(self.tab_7, "")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_19 = QtWidgets.QLabel(self.page_4)
        self.label_19.setGeometry(QtCore.QRect(140, 20, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("margin:auto;")
        self.label_19.setObjectName("label_19")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.page_4)
        self.tabWidget_4.setGeometry(QtCore.QRect(20, 60, 631, 401))
        self.tabWidget_4.setMinimumSize(QtCore.QSize(251, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget_4.setFont(font)
        self.tabWidget_4.setStyleSheet("")
        self.tabWidget_4.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_4.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_4.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget_4.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_4.setUsesScrollButtons(True)
        self.tabWidget_4.setDocumentMode(False)
        self.tabWidget_4.setTabsClosable(False)
        self.tabWidget_4.setMovable(False)
        self.tabWidget_4.setTabBarAutoHide(False)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.label_11 = QtWidgets.QLabel(self.tab_8)
        self.label_11.setGeometry(QtCore.QRect(10, 40, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_20 = QtWidgets.QLabel(self.tab_8)
        self.label_20.setGeometry(QtCore.QRect(10, 90, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_23 = QtWidgets.QLabel(self.tab_8)
        self.label_23.setGeometry(QtCore.QRect(10, 140, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab_8)
        self.label_24.setGeometry(QtCore.QRect(10, 190, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_8)
        self.label_25.setGeometry(QtCore.QRect(10, 250, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.insert_flight_info_number_input = QtWidgets.QLineEdit(self.tab_8)
        self.insert_flight_info_number_input.setGeometry(QtCore.QRect(180, 40, 113, 20))
        self.insert_flight_info_number_input.setStyleSheet("border:1px solid teal;")
        self.insert_flight_info_number_input.setObjectName("insert_flight_info_number_input")
        self.insert_flight_info_departure_input = QtWidgets.QLineEdit(self.tab_8)
        self.insert_flight_info_departure_input.setGeometry(QtCore.QRect(180, 90, 113, 20))
        self.insert_flight_info_departure_input.setStyleSheet("border:1px solid teal;")
        self.insert_flight_info_departure_input.setText("")
        self.insert_flight_info_departure_input.setObjectName("insert_flight_info_departure_input")
        self.insert_flight_info_arrival_input = QtWidgets.QLineEdit(self.tab_8)
        self.insert_flight_info_arrival_input.setGeometry(QtCore.QRect(180, 140, 113, 20))
        self.insert_flight_info_arrival_input.setStyleSheet("border:1px solid teal;")
        self.insert_flight_info_arrival_input.setObjectName("insert_flight_info_arrival_input")
        self.insert_flight_info_all_seats_input = QtWidgets.QLineEdit(self.tab_8)
        self.insert_flight_info_all_seats_input.setGeometry(QtCore.QRect(180, 190, 113, 20))
        self.insert_flight_info_all_seats_input.setStyleSheet("border:1px solid teal;")
        self.insert_flight_info_all_seats_input.setObjectName("insert_flight_info_all_seats_input")
        self.insert_flight_info_date_input = QtWidgets.QLineEdit(self.tab_8)
        self.insert_flight_info_date_input.setGeometry(QtCore.QRect(180, 250, 113, 20))
        self.insert_flight_info_date_input.setStyleSheet("border:1px solid teal;")
        self.insert_flight_info_date_input.setObjectName("insert_flight_info_date_input")
        self.apply_insert_flight_info = QtWidgets.QPushButton(self.tab_8)
        self.apply_insert_flight_info.setGeometry(QtCore.QRect(0, 310, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.apply_insert_flight_info.setFont(font)
        self.apply_insert_flight_info.setStyleSheet("margin:10px;\n"
"border-radius: 15px;\n"
"background-color:teal;\n"
"color:white;\n"
"font-weight:bold;")
        self.apply_insert_flight_info.setObjectName("apply_insert_flight_info")
        self.amount_of_seats_error = QtWidgets.QLabel(self.tab_8)
        self.amount_of_seats_error.setGeometry(QtCore.QRect(320, 190, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.amount_of_seats_error.setFont(font)
        self.amount_of_seats_error.setStyleSheet("color:orange;")
        self.amount_of_seats_error.setText("")
        self.amount_of_seats_error.setObjectName("amount_of_seats_error")
        self.date_insert_error = QtWidgets.QLabel(self.tab_8)
        self.date_insert_error.setGeometry(QtCore.QRect(320, 250, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.date_insert_error.setFont(font)
        self.date_insert_error.setStyleSheet("color:orange;")
        self.date_insert_error.setText("")
        self.date_insert_error.setObjectName("date_insert_error")
        self.number_error = QtWidgets.QLabel(self.tab_8)
        self.number_error.setGeometry(QtCore.QRect(320, 40, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.number_error.setFont(font)
        self.number_error.setStyleSheet("color:orange;")
        self.number_error.setText("")
        self.number_error.setObjectName("number_error")
        self.departure_error = QtWidgets.QLabel(self.tab_8)
        self.departure_error.setGeometry(QtCore.QRect(320, 90, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.departure_error.setFont(font)
        self.departure_error.setStyleSheet("color:orange;")
        self.departure_error.setText("")
        self.departure_error.setObjectName("departure_error")
        self.insert_error = QtWidgets.QLabel(self.tab_8)
        self.insert_error.setGeometry(QtCore.QRect(140, 330, 291, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.insert_error.setFont(font)
        self.insert_error.setStyleSheet("color:orange;")
        self.insert_error.setText("")
        self.insert_error.setObjectName("insert_error")
        self.arrival_error = QtWidgets.QLabel(self.tab_8)
        self.arrival_error.setGeometry(QtCore.QRect(320, 140, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.arrival_error.setFont(font)
        self.arrival_error.setStyleSheet("color:orange;")
        self.arrival_error.setText("")
        self.arrival_error.setObjectName("arrival_error")
        self.tabWidget_4.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.label_21 = QtWidgets.QLabel(self.tab_9)
        self.label_21.setGeometry(QtCore.QRect(20, 30, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_9)
        self.label_22.setGeometry(QtCore.QRect(20, 80, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_27 = QtWidgets.QLabel(self.tab_9)
        self.label_27.setGeometry(QtCore.QRect(20, 180, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_9)
        self.label_28.setGeometry(QtCore.QRect(20, 230, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_26 = QtWidgets.QLabel(self.tab_9)
        self.label_26.setGeometry(QtCore.QRect(20, 130, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.insert_passenger_info_surname_input = QtWidgets.QLineEdit(self.tab_9)
        self.insert_passenger_info_surname_input.setGeometry(QtCore.QRect(180, 30, 113, 20))
        self.insert_passenger_info_surname_input.setStyleSheet("border:1px solid teal;")
        self.insert_passenger_info_surname_input.setObjectName("insert_passenger_info_surname_input")
        self.insert_passenger_info_number_input = QtWidgets.QLineEdit(self.tab_9)
        self.insert_passenger_info_number_input.setGeometry(QtCore.QRect(180, 80, 113, 20))
        self.insert_passenger_info_number_input.setStyleSheet("border:1px solid teal;")
        self.insert_passenger_info_number_input.setObjectName("insert_passenger_info_number_input")
        self.insert_passenger_info_baggage_input = QtWidgets.QLineEdit(self.tab_9)
        self.insert_passenger_info_baggage_input.setGeometry(QtCore.QRect(180, 180, 113, 20))
        self.insert_passenger_info_baggage_input.setStyleSheet("border:1px solid teal;")
        self.insert_passenger_info_baggage_input.setObjectName("insert_passenger_info_baggage_input")
        self.insert_passenger_info_cost_input = QtWidgets.QLineEdit(self.tab_9)
        self.insert_passenger_info_cost_input.setGeometry(QtCore.QRect(180, 230, 113, 20))
        self.insert_passenger_info_cost_input.setStyleSheet("border:1px solid teal;")
        self.insert_passenger_info_cost_input.setObjectName("insert_passenger_info_cost_input")
        self.insert_passenger_info_class_combo = QtWidgets.QComboBox(self.tab_9)
        self.insert_passenger_info_class_combo.setGeometry(QtCore.QRect(188, 130, 101, 22))
        self.insert_passenger_info_class_combo.setObjectName("insert_passenger_info_class_combo")
        self.insert_passenger_info_class_combo.addItem("")
        self.insert_passenger_info_class_combo.addItem("")
        self.insert_passenger_info_class_combo.addItem("")
        self.apply_insert_passenger_info = QtWidgets.QPushButton(self.tab_9)
        self.apply_insert_passenger_info.setGeometry(QtCore.QRect(20, 300, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.apply_insert_passenger_info.setFont(font)
        self.apply_insert_passenger_info.setStyleSheet("margin:10px;\n"
"border-radius: 15px;\n"
"background-color:teal;\n"
"color:white;\n"
"font-weight:bold;")
        self.apply_insert_passenger_info.setObjectName("apply_insert_passenger_info")
        self.passenger_flight_input_error = QtWidgets.QLabel(self.tab_9)
        self.passenger_flight_input_error.setGeometry(QtCore.QRect(320, 80, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passenger_flight_input_error.setFont(font)
        self.passenger_flight_input_error.setStyleSheet("color:orange;")
        self.passenger_flight_input_error.setText("")
        self.passenger_flight_input_error.setObjectName("passenger_flight_input_error")
        self.baggage_cost_input_error = QtWidgets.QLabel(self.tab_9)
        self.baggage_cost_input_error.setGeometry(QtCore.QRect(320, 180, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.baggage_cost_input_error.setFont(font)
        self.baggage_cost_input_error.setStyleSheet("color:orange;")
        self.baggage_cost_input_error.setText("")
        self.baggage_cost_input_error.setObjectName("baggage_cost_input_error")
        self.ticket_cost_input_error = QtWidgets.QLabel(self.tab_9)
        self.ticket_cost_input_error.setGeometry(QtCore.QRect(320, 230, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ticket_cost_input_error.setFont(font)
        self.ticket_cost_input_error.setStyleSheet("color:orange;")
        self.ticket_cost_input_error.setText("")
        self.ticket_cost_input_error.setObjectName("ticket_cost_input_error")
        self.insert_passenger_error = QtWidgets.QLabel(self.tab_9)
        self.insert_passenger_error.setGeometry(QtCore.QRect(150, 310, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.insert_passenger_error.setFont(font)
        self.insert_passenger_error.setStyleSheet("color:orange;")
        self.insert_passenger_error.setText("")
        self.insert_passenger_error.setObjectName("insert_passenger_error")
        self.passenger_surname_input_error = QtWidgets.QLabel(self.tab_9)
        self.passenger_surname_input_error.setGeometry(QtCore.QRect(320, 30, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passenger_surname_input_error.setFont(font)
        self.passenger_surname_input_error.setStyleSheet("color:orange;")
        self.passenger_surname_input_error.setText("")
        self.passenger_surname_input_error.setObjectName("passenger_surname_input_error")
        self.tabWidget_4.addTab(self.tab_9, "")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_14 = QtWidgets.QLabel(self.page_5)
        self.label_14.setGeometry(QtCore.QRect(180, 150, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.page_5)
        self.label_15.setGeometry(QtCore.QRect(180, 200, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.login_input = QtWidgets.QLineEdit(self.page_5)
        self.login_input.setGeometry(QtCore.QRect(280, 150, 113, 20))
        self.login_input.setStyleSheet("border:1px solid teal;")
        self.login_input.setObjectName("login_input")
        self.password_input = QtWidgets.QLineEdit(self.page_5)
        self.password_input.setGeometry(QtCore.QRect(280, 200, 113, 20))
        self.password_input.setStyleSheet("border:1px solid teal;")
        self.password_input.setObjectName("password_input")
        self.log_in_btn = QtWidgets.QPushButton(self.page_5)
        self.log_in_btn.setGeometry(QtCore.QRect(220, 240, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.log_in_btn.setFont(font)
        self.log_in_btn.setStyleSheet("margin:10px;\n"
"border-radius: 15px;\n"
"background-color:teal;\n"
"color:white;\n"
"font-weight:bold;")
        self.log_in_btn.setObjectName("log_in_btn")
        self.login_error = QtWidgets.QLabel(self.page_5)
        self.login_error.setGeometry(QtCore.QRect(170, 310, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.login_error.setFont(font)
        self.login_error.setStyleSheet("color:orange;")
        self.login_error.setText("")
        self.login_error.setObjectName("login_error")
        self.stackedWidget.addWidget(self.page_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action12 = QtWidgets.QAction(MainWindow)
        self.action12.setObjectName("action12")
        self.action12_2 = QtWidgets.QAction(MainWindow)
        self.action12_2.setObjectName("action12_2")
        self.action1_1 = QtWidgets.QAction(MainWindow)
        self.action1_1.setObjectName("action1_1")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(1)
        self.tabWidget_4.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.insert_info.setText(_translate("MainWindow", "Insert info"))
        self.get_info.setText(_translate("MainWindow", "View flight info"))
        self.login.setText(_translate("MainWindow", "Login"))
        self.additional_info.setText(_translate("MainWindow", "Additional info"))
        self.view_info_admin.setText(_translate("MainWindow", "View flight info"))
        self.label_6.setText(_translate("MainWindow", "User"))
        self.label_7.setText(_translate("MainWindow", "Admin"))
        self.label.setText(_translate("MainWindow", "Find flights information by"))
        self.label_2.setText(_translate("MainWindow", "Enter flight number"))
        self.find_info_number_btn.setText(_translate("MainWindow", "Find"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Number"))
        self.find_info_direction_btn.setText(_translate("MainWindow", "Find"))
        self.label_3.setText(_translate("MainWindow", "Departure"))
        self.label_4.setText(_translate("MainWindow", "Arrival"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Direction"))
        self.label_5.setText(_translate("MainWindow", "Enter date"))
        self.find_info_date_btn.setText(_translate("MainWindow", "Find"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Date"))
        self.label_8.setText(_translate("MainWindow", "Enter flight number"))
        self.get_number_of_free_seats_btn.setText(_translate("MainWindow", "Get free seats"))
        self.label_12.setText(_translate("MainWindow", "Number of free seats:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Free seats"))
        self.label_13.setText(_translate("MainWindow", "Sum of the baggage"))
        self.get_baggage_sum_btn.setText(_translate("MainWindow", "Get sum of baggage"))
        self.label_9.setText(_translate("MainWindow", "Enter flight number"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Sum of baggage"))
        self.label_10.setText(_translate("MainWindow", "Find flights information by"))
        self.label_16.setText(_translate("MainWindow", "Enter surname"))
        self.find_info_surname_btn.setText(_translate("MainWindow", "Find"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "Surname"))
        self.find_info_direction_btn_2.setText(_translate("MainWindow", "Find"))
        self.label_17.setText(_translate("MainWindow", "Departure"))
        self.label_18.setText(_translate("MainWindow", "Arrival"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Direction"))
        self.label_19.setText(_translate("MainWindow", "Insert new info into database"))
        self.label_11.setText(_translate("MainWindow", "Enter flight number"))
        self.label_20.setText(_translate("MainWindow", "Departure"))
        self.label_23.setText(_translate("MainWindow", "Arrival"))
        self.label_24.setText(_translate("MainWindow", "Enter amount of seats"))
        self.label_25.setText(_translate("MainWindow", "Enter date"))
        self.apply_insert_flight_info.setText(_translate("MainWindow", "Apply"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_8), _translate("MainWindow", "Flight"))
        self.label_21.setText(_translate("MainWindow", "Enter surname"))
        self.label_22.setText(_translate("MainWindow", "Enter flight number"))
        self.label_27.setText(_translate("MainWindow", "Enter baggae value"))
        self.label_28.setText(_translate("MainWindow", "Enter ticket cost"))
        self.label_26.setText(_translate("MainWindow", "Enter class"))
        self.insert_passenger_info_class_combo.setItemText(0, _translate("MainWindow", "First"))
        self.insert_passenger_info_class_combo.setItemText(1, _translate("MainWindow", "Bussines"))
        self.insert_passenger_info_class_combo.setItemText(2, _translate("MainWindow", "Economy"))
        self.apply_insert_passenger_info.setText(_translate("MainWindow", "Apply"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_9), _translate("MainWindow", "Passenger"))
        self.label_14.setText(_translate("MainWindow", "Login:"))
        self.label_15.setText(_translate("MainWindow", "Password"))
        self.log_in_btn.setText(_translate("MainWindow", "Log in"))
        self.action2.setText(_translate("MainWindow", "2"))
        self.action12.setText(_translate("MainWindow", "11"))
        self.action12_2.setText(_translate("MainWindow", "12"))
        self.action1_1.setText(_translate("MainWindow", "1.1"))
